name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: checkout common submodule
      run: git submodule update --remote
    - name: install dependencies
      run: |
        sudo apt-get -y -qq update
        sudo apt-get -y -qq install cmake ninja-build build-essential
    - name: check gcc version
      run: gcc -v
    - name: make test
      run: |
        cmake -S. -Bbuild -GNinja
        ninja -v -Cbuild
