name: CI

on:
  push:
    branches:
      - test
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

  pull_request:
    branches:
      - test
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install dependencies
      run: |
        sudo apt-get -y -qq update
        sudo apt-get -y -qq install cmake ninja-build
    - name: check gcc version
      run: gcc -v
    - name: test
      run: |
        cmake -S. -Bbuild -GNinja
        ninja -v -Cbuild
