name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: checkout submodules
      run: git submodule update --init --remote --recursive
    - name: install dependencies
      run: |
        sudo apt-get -y -qq update
        sudo apt-get -y -qq install cmake ninja-build
    - name: check gcc version
      run: gcc -v
    - name: make test
      run: |
        cmake -S. -Bbuild -GNinja
        ninja -v -Cbuild
